name: Test (avec phpunit et SonarQube), Build image docker, and deploy PHP app to Azure Web App with Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'webapp45693926'  # Azure Web App name
  DOCKER_IMAGE: 'samirswidi/phpdevoops'  # Docker image name
  PHP_VERSION: '8.x'  # PHP version used

permissions:
  contents: read

jobs:
  test:
    name: Run Tests avec phpUnit et SonarQube 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for SonarCloud analysis

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, intl, pdo, mysqli
          coverage: none
          #installation des dépendances pour test avec phpunit
      - name: Install dependencies 
        run: composer install --no-progress
      - name: Install dependencies
        run: composer install --no-progress
      - name: Run tests using phpunit
        run: vendor/bin/phpunit --testdox tests/GetCurrentYearTest.php
         #Exécuter SonarQube scan pour scanner notre code
      - name: Run SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Depend on the 'test' phase

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                               # Context for Docker build
          file: ./Dockerfile                       # Path to Dockerfile
          push: true                               # Push image to DockerHub
          tags: ${{ env.DOCKER_IMAGE }}:1.0.${{ github.run_number }}

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: docker-build-push  # Depend on Docker build phase
    environment:
      name: 'Development'

    steps:
      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_IMAGE }}:1.0.${{ github.run_number }}
