name: Build, test, and deploy PHP app to Azure Web App with Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'webapp45693926'  # Azure Web App name
  DOCKER_IMAGE: 'samirswidi/phpdevoops'  # Docker image name
  PHP_VERSION: '8.x'  # PHP version used

permissions:
  contents: read

jobs:
  test:
    name: Run Tests and SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for SonarCloud analysis

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, intl, pdo, mysqli
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=samirswidi
            -Dsonar.projectKey=samirswidi_phpdevoops
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number || '' }}
            -Dsonar.pullrequest.branch=${{ github.head_ref || github.ref_name }}
            -Dsonar.pullrequest.base=${{ github.base_ref || 'main' }}

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Depend on the 'test' phase

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout
